apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-certs-job
  namespace: linkerd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-certs-job-role
  namespace: linkerd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-certs-job-binding
  namespace: linkerd
subjects:
  - kind: ServiceAccount
    name: linkerd-certs-job
    namespace: linkerd
roleRef:
  kind: Role
  name: linkerd-certs-job-role
  apiGroup: rbac.authorization.k8s.io
